language: elixir
elixir:
  - 1.8.1
otp_release:
  - 21.1
matrix:
  include:
    - name: "Ecto 2.2"
      env:
        - ECTO_TEST_VERSION="~> 2.2"
    - name: "Ecto 3.0"
      env:
        - ECTO_TEST_VERSION="~> 3.0"